# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SiriTutorials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
 pod 'Alamofire' 

  # Pods for SiriTutorials

end

target 'TriviaIntents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  
  # Pods for TriviaIntents
  
end
